# Generated by Django 4.1.4 on 2023-01-02 14:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('title', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('singer', models.CharField(max_length=50)),
                ('music', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='product.music')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
